twig:
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        max_jobs_on_homepage: '%max_jobs_on_homepage%'
        jobs_web_directory: '%jobs_web_directory%'
knp_paginator:
    template:
        pagination: "@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig"
